name: Firebase Security Rules Deploy

on:
  push:
    branches: [ main ]
    paths:
      - 'firestore.rules'
      - 'storage.rules'
      - 'firebase.json'

jobs:
  deploy-security-rules:
    name: Deploy Security Rules
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy Firestore Security Rules
        run: firebase deploy --only firestore:rules --project cocoai-60a2d
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: Deploy Storage Security Rules
        run: firebase deploy --only storage --project cocoai-60a2d
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
